const RideType = require("../models/rideType");

exports.getRideTypes = async (req, res) => {
  try {
    const rideTypes = await RideType.find({ isActive: true }).sort({
      order: 1,
    });

    const groupedRideTypes = {
      standard: {
        category: "Lynk Standard",
        description: "Standard rides for everyday commuting",
        icon: "local-taxi",
        color: "#2196F3",
        rides: [
          {
            id: "lynk_x",
            name: "Lynk X",
            description: "Budget-friendly everyday rides",
            features: [
              "Budget-friendly",
              "Everyday rides",
              "Comfortable seating",
            ],
            priceModel: "varies",
            basePrice: 50,
            pricePerKm: 12,
            pricePerMin: 1.5,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "car",
            isActive: true,
          },
          {
            id: "lynk_plus",
            name: "Lynk Plus",
            description: "Spacious, newer vehicles with extra comfort",
            features: [
              "Spacious",
              "Newer vehicles",
              "Extra comfort",
              "Professional drivers",
            ],
            priceModel: "varies",
            basePrice: 80,
            pricePerKm: 18,
            pricePerMin: 2,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 3,
            icon: "car",
            isActive: true,
          },
          {
            id: "lynk_xl",
            name: "Lynk XL",
            description:
              "Budget-friendly larger vehicles for up to 6 passengers",
            features: [
              "Budget-friendly",
              "Larger vehicles",
              "Group travel",
              "Extra space",
            ],
            priceModel: "varies",
            basePrice: 100,
            pricePerKm: 20,
            pricePerMin: 2.5,
            capacity: 6,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 4,
            icon: "car",
            isActive: true,
          },
        ],
      },
      economy: {
        category: "Lynk Economy",
        description: "Economy rides with special features and comfort",
        icon: "directions-car",
        color: "#4CAF50",
        rides: [
          {
            id: "lynk_ease",
            name: "LynkEase",
            description: "Smooth, quiet rides with additional comfort",
            features: [
              "Smooth rides",
              "Quiet experience",
              "Additional comfort",
              "Premium interiors",
            ],
            priceModel: "varies",
            basePrice: 70,
            pricePerKm: 15,
            pricePerMin: 1.8,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "car",
            isActive: true,
          },
          {
            id: "lynk_eco",
            name: "Lynk Eco",
            description: "Eco-friendly rides in hybrid or electric vehicles",
            features: [
              "Eco-friendly",
              "Hybrid/Electric",
              "Zero emissions",
              "Green initiative",
            ],
            priceModel: "varies",
            basePrice: 75,
            pricePerKm: 16,
            pricePerMin: 2,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "car",
            isActive: true,
          },
          {
            id: "lynk_pet",
            name: "Lynk Pet",
            description:
              "Pet-friendly rides for passengers traveling with pets",
            features: [
              "Pet-friendly",
              "Pet carrier available",
              "Pet treats",
              "Easy cleanup",
            ],
            priceModel: "varies",
            basePrice: 85,
            pricePerKm: 17,
            pricePerMin: 2,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "pets",
            isActive: true,
          },
        ],
      },
      premium: {
        category: "Lynk Premium",
        description: "Premium luxury rides for special occasions",
        icon: "stars",
        color: "#FF9800",
        rides: [
          {
            id: "lynk_suv",
            name: "Lynk SUV",
            description: "High-end luxury rides with professional drivers",
            features: [
              "High-end luxury",
              "Professional drivers",
              "Premium comfort",
              "VIP service",
            ],
            priceModel: "varies",
            basePrice: 150,
            pricePerKm: 30,
            pricePerMin: 3.5,
            capacity: 6,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 4,
            icon: "car",
            isActive: true,
          },
          {
            id: "lynk_max",
            name: "Lynk Max",
            description: "Vans or large vehicles for events and group travel",
            features: [
              "Large vehicles",
              "Group travel",
              "Event ready",
              "Extra luggage space",
            ],
            priceModel: "varies",
            basePrice: 180,
            pricePerKm: 35,
            pricePerMin: 4,
            capacity: 6,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 6,
            icon: "van",
            isActive: true,
          },
          {
            id: "lynk_taxi",
            name: "Lynk Taxi",
            description: "Traditional friendly Local Taxi",
            features: [
              "Traditional taxi",
              "Friendly drivers",
              "Local knowledge",
              "Quick service",
            ],
            priceModel: "varies",
            basePrice: 60,
            pricePerKm: 14,
            pricePerMin: 1.5,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "local-taxi",
            isActive: true,
          },
        ],
      },
      special: {
        category: "Lynk Special",
        description: "Specialized rides for specific needs",
        icon: "star",
        color: "#9C27B0",
        rides: [
          {
            id: "lynk_access",
            name: "LynkAccess",
            description:
              "Wheelchair-accessible vehicles for passengers with disabilities",
            features: [
              "Wheelchair accessible",
              "Trained drivers",
              "Extra assistance",
              "Priority service",
            ],
            priceModel: "varies",
            basePrice: 120,
            pricePerKm: 25,
            pricePerMin: 3,
            capacity: 4,
            timeEstimate: "Real time in Minutes, wait time",
            luggageCapacity: 2,
            icon: "accessible",
            isActive: true,
          },
        ],
      },
    };

    res.status(200).json({
      success: true,
      message: "Ride types fetched successfully",
      data: groupedRideTypes,
    });
  } catch (error) {
    console.error("Error fetching ride types:", error);
    res.status(500).json({ 
      success: false,
      message: "Server error",
      error: error.message,
    });
  }
};
